development:
  adapter: postgresql
  encoding: unicode
  database: kumbu
  pool: 5
  username: cgichuki
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: kumbu
  username: cgichuki
  password:
  host: localhost