# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Listing.delete_all

Listing.create(title: "Mary Kimani", meeting_venue: "Emacra", image_url: "eleanor.jpg", description: "We regret to announce the death of Rahab Wanjiru (Mama Chege) of Coventry, who went to be with the Lord on 15th January 2014 at Walsgrave Hospital Coventry. She is the mother to Jaden Chege Macharia, daughter to Hannah Wanjiku and late Peter Mwangi, wife to Job Macharia (Baba Chege). Sister to Mike Kariuki Mwangi (Coventry), Catherine Wangari Githinji (Swindon/Gloucester), George Mwichigi and John Mutugu. Sister in-law to Joyce Wanjiku Kariuki (Coventry)." )
Listing.create(title: "George Kimani", meeting_venue: "Emacra", image_url: "eleanor.jpg", description: "We regret to announce the death of Rahab Wanjiru (Mama Chege) of Coventry, who went to be with the Lord on 15th January 2014 at Walsgrave Hospital Coventry. She is the mother to Jaden Chege Macharia, daughter to Hannah Wanjiku and late Peter Mwangi, wife to Job Macharia (Baba Chege). Sister to Mike Kariuki Mwangi (Coventry), Catherine Wangari Githinji (Swindon/Gloucester), George Mwichigi and John Mutugu. Sister in-law to Joyce Wanjiku Kariuki (Coventry)." )
Listing.create(title: "Francis Oduor", meeting_venue: "Emacra", image_url: "eleanor.jpg", description: "We regret to announce the death of Rahab Wanjiru (Mama Chege) of Coventry, who went to be with the Lord on 15th January 2014 at Walsgrave Hospital Coventry. She is the mother to Jaden Chege Macharia, daughter to Hannah Wanjiku and late Peter Mwangi, wife to Job Macharia (Baba Chege). Sister to Mike Kariuki Mwangi (Coventry), Catherine Wangari Githinji (Swindon/Gloucester), George Mwichigi and John Mutugu. Sister in-law to Joyce Wanjiku Kariuki (Coventry)." )
Listing.create(title: "Violet Maranga", meeting_venue: "Emacra", image_url: "eleanor.jpg", description: "We regret to announce the death of Rahab Wanjiru (Mama Chege) of Coventry, who went to be with the Lord on 15th January 2014 at Walsgrave Hospital Coventry. She is the mother to Jaden Chege Macharia, daughter to Hannah Wanjiku and late Peter Mwangi, wife to Job Macharia (Baba Chege). Sister to Mike Kariuki Mwangi (Coventry), Catherine Wangari Githinji (Swindon/Gloucester), George Mwichigi and John Mutugu. Sister in-law to Joyce Wanjiku Kariuki (Coventry)." )
